name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Run flake8
      run: |
        flake8 server.py all_labs/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 server.py all_labs/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Run unittest
      run: |
        python -m unittest discover -s tests -p "*.py"
